modLoader="javafml"
license="mit"
issueTrackerURL="https://github.com/codeka/conduits/issues"
loaderVersion="[39,)"

[[mods]]
modId="justconduits"
version="${file.jarVersion}"
displayName="Just Conduits"
displayURL="https://github.com/codeka/conduits"
#credits=""
authors="Dean Harding (dean@codeka.com)"
description='''
Just Conduits is... just conduits. Inspired by EnderIO conduits, we allow you to send items, fluids, power and \
redstone signals in a single block space. Powerful filtering and channel system is the icing on the cake.
'''

# A dependency
#[[dependencies.examplemod]]
#    modId="forge" #mandatory
#    mandatory=true
#    versionRange="[39,)" #mandatory
#    ordering="NONE"
#    side="BOTH"
